import { Navbar } from './components/navbar';
import type { Metadata } from 'next';
import type { FC, ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProperties = Readonly<{
  children: ReactNode;
}>;

const RootLayout: FC<RootLayoutProperties> = ({ children }) => (
  <html lang="en">
    <body className="flex flex-col h-screen divide-y">
      <Navbar />
      {children}
    </body>
  </html>
);

export default RootLayout;
